// GENERATED by `yarn cooldowns` — do not edit by hand.
//
// Seconds from one required kick to the next, per spell id. Only confident estimates land here, so
// an untrustworthy number never silently drives a warning.
//
// Correct or exclude entries in spellCooldowns.ts — patches there win and survive re-running.

export const minedCooldowns: Record<number, number> = {
  1289416: 7.5, // fang High Evolutionist / Ula'tek's Chosen — Envenom = 5s + 2.5s cast
  1307567: 7.5, // fang High Evolutionist / Ula'tek's Chosen — Mass Envenom = 5s + 2.5s cast
  1294557: 24.5, // fang Primal Serpent — Piercing Hiss = 20.5s + 4s cast
  267763: 20.5, // kr Half-Finished Mummy — Wretched Discharge = 16.5s + 4s cast
  270492: 24, // kr Phantom Hex Priest — Hex = 20.5s + 3.5s cast
  1295125: 8.5, // kr Phantom Hex Priest — Spectral Bolt = 6s + 2.5s cast
  1294972: 7.5, // kr Queen Wasi — Soul Bolt = 5s + 2.5s cast
  269369: 12.5, // kr Reban — Deathly Roar = 8.5s + 4s cast
  269972: 22.5, // kr Risen Hexer — Hex Volley = 19s + 3.5s cast
  1294815: 8.5, // kr Risen Hexer — Shadowfrost Bolt = 6s + 2.5s cast
  270901: 18.5, // kr Seneschal M'bara — Unholy Mending = 16s + 2.5s cast
  267273: 24.5, // kr Zanazal the Wise — Poison Nova = 20.5s + 4s cast
  1214980: 20, // murd Fel Invoker — Health Funnel
  1216571: 6, // murd Felonious Mage — Fel Missiles
  474375: 11.5, // murd Lithiel Cinderfury — Chaos Bolt = 8.5s + 3s cast
  1201554: 26.5, // murd Seductive Sayaad — Seduction = 23.5s + 3s cast
  1223204: 6.5, // murd Unleashed Imp / Wild Imp — Felfire Burst = 5s + 1.5s cast
  1214922: 23, // murd Wrathguard Flayer — Fel Rage = 19.5s + 3.5s cast
  734276: 42, // murd Zaen Bladesorrow — Murder in a Row
  1305955: 17.5, // rlp Blazebound Destroyer — Fiery Blast = 13.5s + 4s cast
  373017: 9, // rlp Blazebound Firestorm — Blaze Volley = 5.5s + 3.5s cast
  371984: 8, // rlp Flashfrost Chillweaver — Frostbolt = 5.5s + 2.5s cast
  372743: 28, // rlp Flashfrost Chillweaver — Ice Shield
  372808: 7.5, // rlp Melidrussa Chillworn — Frigid Shard = 5s + 2.5s cast
  384194: 8.5, // rlp Primalist Cinderweaver — Cinderbolt = 6s + 2.5s cast
  392576: 27, // rlp Tempest Channeler — Thunder Blast = 23s + 4s cast
  1310683: 8, // tos Brood Tender — Venom Bolt = 5.5s + 2.5s cast
  1293307: 16.5, // tos Faithless Subjugator — Addle Mind
  1308148: 20.5, // tos Poisonous Viper — Cytotoxin
  1291262: 8.5, // tos Storm Adept / Imbued Stormcaller — Lightning Bolt = 6s + 2.5s cast
  267027: 15, // tos Toxic Viper — Poison Spit = 11s + 4s cast
  268013: 23, // tos Twisted Hexxer — Flame Shock = 19s + 4s cast
  1302158: 12.5, // tos Twisted Hexxer — Flame Shock = 8.5s + 4s cast
  1235616: 9, // vale Kezkitt — Light Bolt = 6.5s + 2.5s cast
  1238232: 8.5, // vale Leafy Grovecrawler — Seed Shot = 6s + 2.5s cast
  1238294: 25, // vale Lightfeather Petalwing — Disorienting Screech = 21s + 4s cast
  1238158: 19.5, // vale Lightgorged Lasher — Lightbloom Pollination
  1247669: 10, // vale Lightspawn Lasher — Lightspore Shot = 7.5s + 2.5s cast
  1239821: 9, // vale Lightwarden Ruia — Warden's Wrath = 7s + 2s cast
  1238063: 8, // vale Radiant Spellsower — Light Bolt = 5.5s + 2.5s cast
  1301834: 30, // vale Radiant Spellsower — Light Bolt Volley = 26s + 4s cast
  1249621: 24, // void Angry Krolusk — Violent Sand = 21s + 3s cast
  1310324: 21.5, // void Devouring Brutalizer / Voidminder — Mending Void
  1298899: 25, // void Dominated Brawler — Demoralizing Shout = 21s + 4s cast
  1228176: 8, // void Enthralled Shaman — Lava Bolt = 5.5s + 2.5s cast
  1233398: 24, // void Kilivore Screamer — Mad Shriek = 20.5s + 3.5s cast
  1299938: 9, // void Voidtouched Magi — Shadowbolt Volley = 5s + 4s cast
}
