#!/usr/bin/env python3
"""
Generate the in-game portrait renderer + crop manifest for one or more dungeons.

Portraits are keyed by NPC id and stored at public/npc_portraits/<npcId>.png.
The npcId -> displayId mapping is read straight out of the MythicDungeonTools
submodule (every enemy carries a "displayId"), so there is NO external lookup:
not wow.tools (dead), not wago.tools (its Creature.db2 only holds a ~23k client
subset, missing dungeon trash/bosses), not WoWhead scraping. MDT is the same
source the app's dungeon data is built from, so it is authoritative and current.

Outputs (into this folder):
  - run_ingame.lua   paste into the WoWLua addon (/lua) and hit Run
  - manifest.json    ordered [{npcId, displayId, name, dungeon}] + layout config,
                     consumed by crop.py so tile order stays in lockstep

Usage:
  python3 generate.py                 # all known dungeons, only MISSING portraits
  python3 generate.py fang murd        # just these dungeon keys
  python3 generate.py --all            # include NPCs that already have a portrait
"""

import json
import os
import re
import sys
from datetime import datetime, timezone

# --- Layout config (MUST match crop.py; also written into manifest.json) ------
PORTRAIT_SIZE = 64   # output portrait size in px (matches existing portraits)
GAP = 8              # black px between tiles; the safety margin for crop recenter
MAX_TILES = 34       # portraits per screenshot (fewer => each batch loads faster)
SETTLE_SECONDS = 4   # wait before each screenshot so portrait models finish loading
                     # (they stream in async; too short => trailing tiles come out
                     #  black). Raise this, or lower MAX_TILES, if any tiles are blank.

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
MDT_DIR = os.path.join(REPO_ROOT, "MythicDungeonTools")
PORTRAITS_DIR = os.path.join(REPO_ROOT, "public", "npc_portraits")

# Fallback if we can't parse it out of mdtDungeons.ts (kept in sync automatically).
FALLBACK_DUNGEON_PATHS = {
    "murd": "Midnight/MurderRow",
    "nalo": "Midnight/DenOfNalorakk",
    "vale": "Midnight/TheBlindingVale",
    "void": "Midnight/VoidscarArena",
    "fang": "Midnight/AltarOfFangs",
    "rlp": "Midnight/RubyLifePools",
    "tos": "Midnight/TempleOfSethraliss",
    "kr": "Midnight/KingsRest",
}


def load_dungeon_paths():
    """Reuse the dungeon->lua-path map defined in scripts/mdtDungeons.ts."""
    ts_path = os.path.join(REPO_ROOT, "scripts", "mdtDungeons.ts")
    try:
        text = open(ts_path, encoding="utf-8").read()
    except OSError:
        return dict(FALLBACK_DUNGEON_PATHS)
    block = re.search(r"dungeonPaths\s*=\s*new Map[^[]*\[(.*?)\]\s*\)", text, re.S)
    scope = block.group(1) if block else text
    pairs = re.findall(r"\[\s*'(\w+)'\s*,\s*'([^']+)'\s*\]", scope)
    return dict(pairs) if pairs else dict(FALLBACK_DUNGEON_PATHS)


def parse_mdt_enemies(lua_path):
    """Return ordered [(npcId, displayId, name)] for a dungeon's MDT lua.

    The export is regular: each enemy block has "name", then "id", then a single
    "displayId" before the next enemy's "id". We walk the tokens in file order and
    pair each id with the first displayId that follows it.
    """
    text = open(lua_path, encoding="utf-8").read()
    token = re.compile(r'\["(id|displayId|name)"\]\s*=\s*(?:"([^"]*)"|(-?\d+))')
    enemies = []
    cur_id = None
    cur_name = None
    for m in token.finditer(text):
        key = m.group(1)
        str_val, num_val = m.group(2), m.group(3)
        if key == "name":
            cur_name = str_val
        elif key == "id":
            cur_id = int(num_val)
        elif key == "displayId" and cur_id is not None:
            enemies.append((cur_id, int(num_val), cur_name))
            cur_id = None
            cur_name = None
    return enemies


def existing_portrait_ids():
    if not os.path.isdir(PORTRAITS_DIR):
        return set()
    return {os.path.splitext(f)[0] for f in os.listdir(PORTRAITS_DIR) if f.endswith(".png")}


LUA_TEMPLATE = """\
-- AUTO-GENERATED by scripts/npcPortraits/generate.py -- do not edit by hand.
-- Paste this whole block into the WoWLua addon (open with /lua) and hit Run.
-- It renders {count} NPC portraits as a grid of tiles on a black backdrop and
-- takes screenshot(s). Then run crop.py to slice them into public/npc_portraits.
--
-- Requirements for pixel-accurate tiles:
--   * Graphics > "Render Scale" = 100% (no dynamic resolution)
--   * Screenshots as TGA (lossless):  /console screenshotFormat tga
--   * Don't press Alt-Z (hiding the UI hides these frames too)

local displayIds = {{
{display_ids}
}}

-- Layout -- keep in lockstep with manifest.json / crop.py.
local portraitSize = {portrait_size}
local gap          = {gap}
local cellSize     = portraitSize + gap
local maxTiles     = {max_tiles}

-- Physical render resolution, auto-detected.
local resX, resY = GetPhysicalScreenSize()

local tilesX = math.floor(resX / cellSize)
local tilesY = math.floor(resY / cellSize)
local numTilesNeeded       = #displayIds
local numTilesAvailable    = math.min(maxTiles, tilesX * tilesY)
local numScreenshotsNeeded = math.ceil(numTilesNeeded / numTilesAvailable)
local numFramesNeeded      = math.min(numTilesNeeded, numTilesAvailable)

-- Frame scale so that 1 local unit == 1 physical pixel (=> tiles are exact px).
local frameScale = 768 / resY / UIParent:GetScale()

-- Fullscreen black backdrop. Anchored to WorldFrame (which always spans the whole
-- physical screen) so no world/UI pixels bleed in, even if UIParent is inset.
local backdrop = CreateFrame("Frame", nil, UIParent)
backdrop:SetFrameStrata("FULLSCREEN_DIALOG")
backdrop:SetPoint("TOPLEFT", WorldFrame, "TOPLEFT", 0, 0)
backdrop:SetPoint("BOTTOMRIGHT", WorldFrame, "BOTTOMRIGHT", 0, 0)
local backdropTex = backdrop:CreateTexture(nil, "BACKGROUND")
backdropTex:SetColorTexture(0, 0, 0, 1)
backdropTex:SetAllPoints(backdrop)

-- Tiles are anchored to UIParent (that's what the pixel-perfect scale assumes).
-- If UIParent is inset from the screen the whole grid shifts, but crop.py detects
-- the grid's actual origin, so that's fine.
local frames = {{}}
for i = 1, numFramesNeeded do
   local col = (i - 1) % tilesX
   local row = math.floor((i - 1) / tilesX)

   local frame = CreateFrame("Frame", nil, UIParent)
   frame:SetSize(portraitSize, portraitSize)
   frame:SetScale(frameScale)
   frame:SetFrameStrata("TOOLTIP")
   frame:SetPoint("TOPLEFT", UIParent, "TOPLEFT", col * cellSize, -row * cellSize)

   local portrait = frame:CreateTexture(nil, "ARTWORK")
   portrait:SetAllPoints(frame)

   frame.portrait = portrait
   table.insert(frames, frame)
end

local function cleanup()
   backdrop:Hide()
   for _, f in ipairs(frames) do f:Hide() end
end

-- Escape hatch if anything hangs: /npcp removes everything (no /reload needed).
SLASH_NPCPORTRAITS1 = "/npcp"
SlashCmdList["NPCPORTRAITS"] = cleanup

local function renderBatch(shotsDone)
   local startIndex = shotsDone * numTilesAvailable + 1
   local remaining  = numTilesNeeded - (shotsDone * numTilesAvailable)
   local endIndex   = startIndex + math.min(remaining, numTilesAvailable) - 1
   for i = startIndex, endIndex do
      local frame = frames[i - startIndex + 1]
      frame:Show()
      SetPortraitTextureFromCreatureDisplayID(frame.portrait, displayIds[i])
   end
   for i = endIndex - startIndex + 2, numFramesNeeded do
      frames[i]:Hide()
   end
   print("|cff00ff00[npcPortraits]|r Rendering " .. startIndex .. "-" .. endIndex ..
         " (screenshot " .. (shotsDone + 1) .. "/" .. numScreenshotsNeeded .. ")...")
end

-- State machine: render -> (settleInterval) -> screenshot -> (shotInterval) -> render/cleanup
-- Only the pre-screenshot wait needs to be long (models stream in async).
-- The post-screenshot wait is just long enough for the file to write.
local settleInterval = {settle_seconds}
local shotInterval   = 0.5
local timeSum = settleInterval   -- fire render immediately on first frame
local shotsDone = 0
local phase = "render"

local function onUpdate(self, elapsed)
   timeSum = timeSum + elapsed
   local needed = (phase == "shoot") and settleInterval or shotInterval
   if timeSum < needed then return end
   timeSum = 0

   if phase == "render" then
      renderBatch(shotsDone)
      phase = "shoot"
   elseif phase == "shoot" then
      Screenshot()
      shotsDone = shotsDone + 1
      phase = (shotsDone >= numScreenshotsNeeded) and "cleanup" or "render"
   elseif phase == "cleanup" then
      cleanup()
      self:SetScript("OnUpdate", nil)
      print("|cff00ff00[npcPortraits]|r Done - took " .. shotsDone ..
            " screenshot(s). Now run crop.py.")
   end
end

local eventFrame = CreateFrame("Frame", nil, UIParent)
eventFrame:SetScript("OnUpdate", onUpdate)

print("|cff00ff00[npcPortraits]|r Loaded " .. numTilesNeeded .. " portraits @ " .. resX .. "x" ..
      resY .. ", " .. numFramesNeeded .. " tiles/shot, " .. numScreenshotsNeeded ..
      " screenshot(s). Type /npcp to abort.")
"""


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    include_all = "--all" in sys.argv[1:]

    dungeon_paths = load_dungeon_paths()
    keys = args if args else list(dungeon_paths.keys())

    unknown = [k for k in keys if k not in dungeon_paths]
    if unknown:
        sys.exit(f"Unknown dungeon key(s): {', '.join(unknown)}\n"
                 f"Known: {', '.join(dungeon_paths)}")

    have = existing_portrait_ids()
    seen = set()
    portraits = []
    print(f"{'dungeon':8} {'enemies':>7} {'selected':>9}")
    for key in keys:
        lua_path = os.path.join(MDT_DIR, f"{dungeon_paths[key]}.lua")
        if not os.path.isfile(lua_path):
            sys.exit(f"MDT lua not found: {lua_path}\n"
                     f"Is the MythicDungeonTools submodule checked out/updated?")
        enemies = parse_mdt_enemies(lua_path)
        selected = 0
        for npc_id, display_id, name in enemies:
            if npc_id in seen:
                continue
            if not include_all and str(npc_id) in have:
                continue
            if display_id == 0:
                print(f"  ! skipping npc {npc_id} ({name}) - displayId is 0")
                continue
            seen.add(npc_id)
            portraits.append({
                "npcId": npc_id,
                "displayId": display_id,
                "name": name,
                "dungeon": key,
            })
            selected += 1
        print(f"{key:8} {len(enemies):>7} {selected:>9}")

    if not portraits:
        print("\nNothing to generate - every requested NPC already has a portrait "
              "(use --all to force).")
        return

    manifest = {
        "generatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "portraitSize": PORTRAIT_SIZE,
        "gap": GAP,
        "maxTiles": MAX_TILES,
        "portraits": portraits,
    }
    manifest_path = os.path.join(SCRIPT_DIR, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    display_ids = ",\n".join(f"   {p['displayId']}" for p in portraits)
    lua = LUA_TEMPLATE.format(
        count=len(portraits),
        display_ids=display_ids,
        portrait_size=PORTRAIT_SIZE,
        gap=GAP,
        max_tiles=MAX_TILES,
        settle_seconds=SETTLE_SECONDS,
    )
    lua_path = os.path.join(SCRIPT_DIR, "run_ingame.lua")
    with open(lua_path, "w", encoding="utf-8") as f:
        f.write(lua)

    per_shot = MAX_TILES
    shots = -(-len(portraits) // per_shot)  # ceil, rough (real value depends on res)
    print(f"\nWrote {len(portraits)} portraits to:")
    print(f"  {os.path.relpath(manifest_path, REPO_ROOT)}")
    print(f"  {os.path.relpath(lua_path, REPO_ROOT)}")
    print(f"\nNext: paste run_ingame.lua into the WoWLua addon in-game and Run it "
          f"(~{shots} screenshot(s)), then: python3 crop.py")


if __name__ == "__main__":
    main()
