// Mines interrupt intervals from Warcraft Logs and writes src/data/spells/spellCooldownsMined.ts.
//
// Measures seconds from one required kick to the next, preferring:
//   1. post-kick — landed interrupt to that mob instance's next cast start, plus the cast time the
//      kicker has to react in. Needs no modelling: it folds in the spell's cooldown and the
//      interrupt lockout, whichever binds.
//   2. natural recast — cast start to cast start for completed casts, when the spell was never
//      kicked enough to measure directly. Already includes one cast time, so none is added.
//
// Recast alone would be wrong for spam casters: ToS Venom Bolt free-casts every 3.5s, but once
// kicked cannot retry for ~5s, and the kicker then has its 2.5s cast to react — 7.5s, exactly
// soloable by two 15s melee kicks.
//
// Only confident estimates are written; the rest appear in the coverage table for a hand patch in
// spellCooldowns.ts.
//
// Usage:
//   yarn rankings:download                      # populates the gitignored src/data/sampleRoutes/
//   yarn cooldowns                              # every dungeon, sampled from that corpus
//   yarn cooldowns nalo                         # one dungeon from the corpus
//   yarn cooldowns nalo <reportCode> <fightId>  # one specific log, no corpus needed

import { writeFile } from 'fs/promises'
import * as path from 'path'
import { getGrimoireSpell } from 'grimoire-wow'
import { type DungeonKey, dungeonKeys } from '../src/data/dungeonKeys.ts'
import { mdtDungeons } from '../src/data/mdtDungeons.ts'
import { readDungeonRoutes } from './rankingsFiles.ts'
import { getDirname } from '../server/files.ts'
import { roundTo } from '../src/util/numbers.ts'
import { MELEE_LOCKOUT } from '../src/util/interrupts.ts'
import { fetchWcl, getFight, type PagedEventsQuery } from '../server/wcl.ts'

const MINED_PATH = path.join(
  getDirname(import.meta.url),
  '../src/data/spells/spellCooldownsMined.ts',
)

const HEADER = `// GENERATED by \`yarn cooldowns\` — do not edit by hand.
//
// Seconds from one required kick to the next, per spell id. Only confident estimates land here, so
// an untrustworthy number never silently drives a warning.
//
// Correct or exclude entries in spellCooldowns.ts — patches there win and survive re-running.
`

/** Confident estimates from this run, spell id -> mined cooldown. */
const mined = new Map<number, { cooldown: number; samples: number }>()

/** Fights sampled per dungeon. Each costs one getFight plus a few paged event queries. */
const FIGHTS_PER_DUNGEON = 10

/** Below this many usable deltas, an estimate isn't worth trusting. */
const MIN_SAMPLES = 5

/** Deltas beyond this multiple of the median are leashes, target swaps, adds or re-pulls. */
const OUTLIER_FACTOR = 3

/** Deltas are binned to this many seconds before taking the mode. Raw ms are never equal. */
const BIN_SECONDS = 0.5

/**
 * Estimates are floored at the melee lockout because shorter-lockout interrupts otherwise
 * contaminate them: Avenger's Shield locks out only 3s, dragging spam casters below anything a
 * melee kicker could sustain. Real cooldowns are longer, so unaffected.
 */
const LOCKOUT_FLOOR = MELEE_LOCKOUT

type CastEvent = {
  timestamp: number
  type: string
  sourceID: number
  sourceInstance?: number
  abilityGameID: number
}

type InterruptEvent = {
  timestamp: number
  targetID: number
  targetInstance?: number
  extraAbilityGameID: number
}

type SpellSamples = {
  gameId: number
  abilityId: number
  /** One entry per (mob instance, fight), each a sorted list of that instance's cast events. */
  timelines: CastEvent[][]
  /** Seconds from a landed interrupt to that same mob instance's next cast attempt. */
  postKick: number[]
}

const filterDungeonKey = process.argv[2] as DungeonKey | undefined
const explicitCode = process.argv[3]
const explicitFightId = process.argv[4]

if (filterDungeonKey && !dungeonKeys.includes(filterDungeonKey)) {
  console.error(`Unknown dungeon key "${filterDungeonKey}". Known: ${dungeonKeys.join(', ')}`)
  process.exit(1)
}

if (explicitCode && !filterDungeonKey) {
  console.error('A dungeon key is required when passing an explicit report code.')
  process.exit(1)
}

const spellName = (id: number): string => {
  try {
    return getGrimoireSpell(id).name
  } catch {
    return `spell ${id}`
  }
}

/**
 * Cast time in seconds — the kicker's reaction window, since they have until the cast lands rather
 * than until it starts. Grimoire stores milliseconds. Channels report 0 despite being interruptible
 * for their whole duration, so their demand comes out conservative.
 */
const castTime = (id: number): number => {
  try {
    return (getGrimoireSpell(id).castTime ?? 0) / 1000
  } catch {
    return 0
  }
}

/** Mob game id -> interruptible spell ids, from the shipped MDT data. */
function interruptibleSpells(dungeonKey: DungeonKey): Map<number, Set<number>> {
  const byMob = new Map<number, Set<number>>()

  for (const enemy of mdtDungeons[dungeonKey].enemies) {
    const ids = enemy.spells
      .filter((spell) => spell.attributes.includes('interruptible'))
      .map((spell) => spell.id)

    if (ids.length) {
      byMob.set(enemy.id, new Set(ids))
    }
  }

  return byMob
}

const castsQuery = (code: string, fightId: number, startTime: number) => `
query {
  reportData {
    report(code:"${code}") {
      events(fightIDs:${fightId},
             dataType:Casts,
             hostilityType:Enemies,
             useAbilityIDs:true,
             useActorIDs:true,
             startTime:${startTime},
             endTime:999999999)
      {
        nextPageTimestamp,
        data,
      }
    }
  }
}
`

// Interrupts are logged with the *player* as the source, so they come from the Friendlies side.
const interruptsQuery = (code: string, fightId: number, startTime: number) => `
query {
  reportData {
    report(code:"${code}") {
      events(fightIDs:${fightId},
             dataType:Interrupts,
             hostilityType:Friendlies,
             useAbilityIDs:true,
             useActorIDs:true,
             startTime:${startTime},
             endTime:999999999)
      {
        nextPageTimestamp,
        data,
      }
    }
  }
}
`

async function fetchPaged<T>(toQuery: (startTime: number) => string): Promise<T[]> {
  const events: T[] = []
  let nextTimestamp: number | null = 0

  while (nextTimestamp !== null) {
    const data: PagedEventsQuery<T> = await fetchWcl<PagedEventsQuery<T>>(toQuery(nextTimestamp))

    events.push(...data.reportData.report.events.data)
    nextTimestamp = data.reportData.report.events.nextPageTimestamp
  }

  return events
}

const fetchCasts = (code: string, fightId: number) =>
  fetchPaged<CastEvent>((t) => castsQuery(code, fightId, t))

const fetchInterrupts = (code: string, fightId: number) =>
  fetchPaged<InterruptEvent>((t) => interruptsQuery(code, fightId, t))

/**
 * WCL emits one row per target for multi-target casts, so one cast can appear as a run of identical
 * events sharing a timestamp. Left in, they produce 0s deltas that drag the median to zero.
 */
function dedupe(timeline: CastEvent[]): CastEvent[] {
  return timeline.filter(
    (event, i) =>
      i === 0 ||
      event.timestamp !== timeline[i - 1]!.timestamp ||
      event.type !== timeline[i - 1]!.type,
  )
}

/**
 * Deltas between cast starts, keeping only those where the earlier cast completed (a begincast
 * followed by a cast). For the spells worth kicking a majority of casts get interrupted, and the
 * post-lockout retry comes far sooner than the real cycle — left in, those become the mode.
 */
function completedDeltas(sorted: CastEvent[]): number[] {
  const timeline = dedupe(sorted)
  const hasBeginCast = timeline.some((event) => event.type === 'begincast')

  // Channels emit no begincast, so their cast events are the only starts available.
  if (!hasBeginCast) {
    const starts = timeline.filter((event) => event.type === 'cast')
    return starts
      .slice(1)
      .map((event, i) => (event.timestamp - starts[i]!.timestamp) / 1000)
      .filter((delta) => delta > 0)
  }

  const deltas: number[] = []
  let previousStart: number | null = null

  for (let i = 0; i < timeline.length; ++i) {
    const event = timeline[i]!
    if (event.type !== 'begincast') {
      continue
    }

    const completed = timeline[i + 1]?.type === 'cast'
    if (previousStart !== null) {
      const delta = (event.timestamp - previousStart) / 1000
      if (delta > 0) {
        deltas.push(delta)
      }
    }

    previousStart = completed ? event.timestamp : null
  }

  return deltas
}

const median = (values: number[]): number => {
  const sorted = [...values].sort((a, b) => a - b)
  const mid = Math.floor(sorted.length / 2)
  return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2
}

function histogram(deltas: number[]): Map<number, number> {
  const bins = new Map<number, number>()

  for (const delta of deltas) {
    const bin = Math.round(delta / BIN_SECONDS) * BIN_SECONDS
    bins.set(bin, (bins.get(bin) ?? 0) + 1)
  }

  return bins
}

async function guessDungeonCooldowns(dungeonKey: DungeonKey) {
  const byMob = interruptibleSpells(dungeonKey)
  if (!byMob.size) {
    console.log(`\n${dungeonKey}: no interruptible spells in MDT data, skipping`)
    return
  }

  const fights: Array<{ code: string; fightID: number }> = explicitCode
    ? [{ code: explicitCode, fightID: Number(explicitFightId) }]
    : readDungeonRoutes(dungeonKey)
        .filter((route) => route.wclRanking?.report.code)
        .slice(0, FIGHTS_PER_DUNGEON)
        .map((route) => route.wclRanking!.report)

  if (!fights.length) {
    console.log(
      `\n${dungeonKey}: no cached ranked routes. Run \`yarn rankings:download\` first, or pass a ` +
        `log directly: \`yarn cooldowns ${dungeonKey} <reportCode> <fightId>\``,
    )
    return
  }

  console.log(`\n${'='.repeat(78)}\n${dungeonKey} — sampling ${fights.length} fights\n`)

  const samples = new Map<string, SpellSamples>()

  for (const { code, fightID } of fights) {
    try {
      const fight = await getFight(code, fightID)

      // sourceID identifies the NPC type; sourceInstance distinguishes copies. Without the
      // instance, every copy of a mob interleaves into one timeline and the deltas turn to noise.
      const actorToGameId = new Map<number, number>()
      for (const dungeonPull of fight.dungeonPulls ?? []) {
        for (const npc of dungeonPull.enemyNPCs) {
          actorToGameId.set(npc.id, npc.gameID)
        }
      }

      const timelines = new Map<string, CastEvent[]>()
      for (const event of await fetchCasts(code, fightID)) {
        if (event.type !== 'begincast' && event.type !== 'cast') {
          continue
        }

        const gameId = actorToGameId.get(event.sourceID)
        if (gameId === undefined || !byMob.get(gameId)?.has(event.abilityGameID)) {
          continue
        }

        // Fight is part of the key so instances from different logs never merge.
        const key = `${gameId}|${event.abilityGameID}|${event.sourceInstance ?? 0}|${code}-${fightID}`
        const timeline = timelines.get(key)
        if (timeline) {
          timeline.push(event)
        } else {
          timelines.set(key, [event])
        }
      }

      for (const timeline of timelines.values()) {
        timeline.sort((a, b) => a.timestamp - b.timestamp)
      }

      for (const [key, timeline] of timelines) {
        const [gameId, abilityId] = key.split('|').map(Number) as [number, number]
        const spellKey = `${gameId}|${abilityId}`

        const existing = samples.get(spellKey)
        if (existing) {
          existing.timelines.push(timeline)
        } else {
          samples.set(spellKey, { gameId, abilityId, timelines: [timeline], postKick: [] })
        }
      }

      // The measurement that matters: once a kick lands, how long until this mob can try again.
      for (const interrupt of await fetchInterrupts(code, fightID)) {
        const gameId = actorToGameId.get(interrupt.targetID)
        if (gameId === undefined || !byMob.get(gameId)?.has(interrupt.extraAbilityGameID)) {
          continue
        }

        const key = `${gameId}|${interrupt.extraAbilityGameID}|${interrupt.targetInstance ?? 0}|${code}-${fightID}`
        const next = timelines.get(key)?.find((event) => event.timestamp > interrupt.timestamp)

        if (next) {
          samples
            .get(`${gameId}|${interrupt.extraAbilityGameID}`)
            ?.postKick.push((next.timestamp - interrupt.timestamp) / 1000)
        }
      }

      console.log(`  ${code}-${fightID}: ok`)
    } catch (e) {
      console.error(`  ${code}-${fightID}: ${e instanceof Error ? e.message : e}`)
    }
  }

  report(dungeonKey, byMob, samples)
}

function report(
  dungeonKey: DungeonKey,
  byMob: Map<number, Set<number>>,
  samples: Map<string, SpellSamples>,
) {
  const mobNames = new Map(mdtDungeons[dungeonKey].enemies.map((enemy) => [enemy.id, enemy.name]))
  const rows: string[] = []

  for (const [gameId, spellIds] of byMob) {
    for (const abilityId of spellIds) {
      const sample = samples.get(`${gameId}|${abilityId}`)
      const label = `${mobNames.get(gameId) ?? gameId} — ${spellName(abilityId)} (${abilityId})`

      if (!sample) {
        rows.push(`${abilityId}\t-\t-\tNO DATA\t${label}`)
        continue
      }

      const estimate = (values: number[]) => {
        if (!values.length) {
          return null
        }

        const cutoff = median(values) * OUTLIER_FACTOR
        const kept = values.filter((value) => value <= cutoff)
        const bins = [...histogram(kept)].sort((a, b) => b[1] - a[1] || a[0] - b[0])
        const [topBin, topCount] = bins[0]!

        // With scattered samples every bin holds one value, and "most common bin, ties to the
        // smallest" collapses to "the minimum", biasing sparse spells low. Use the median there.
        const mode = topCount >= 2 ? topBin : Math.round(median(kept) / BIN_SECONDS) * BIN_SECONDS

        return {
          mode,
          statistic: topCount >= 2 ? 'mode' : 'median',
          samples: kept.length,
          bins,
          dropped: values.length - kept.length,
        }
      }

      const postKick = estimate(sample.postKick)
      const natural = estimate(sample.timelines.flatMap(completedDeltas))

      // Post-kick wins wherever it has the samples; the recast fallback measures a mob nobody was
      // kicking. When neither clears MIN_SAMPLES take whichever has more, rather than nothing: a
      // mob whose every cast gets kicked completes none, so it has no recast at all, and
      // preferring that null discarded the only measurement there was.
      const better =
        !postKick || (natural && natural.samples > postKick.samples) ? natural : postKick
      const chosen =
        postKick && postKick.samples >= MIN_SAMPLES
          ? postKick
          : natural && natural.samples >= MIN_SAMPLES
            ? natural
            : better

      const source = chosen === postKick ? 'post-kick' : 'recast'
      const cast = castTime(abilityId)

      // Cast time is added only on the post-kick path, which measures interrupt -> next cast
      // *start*. The recast path measures start -> start and already contains one.
      const value = chosen
        ? source === 'post-kick'
          ? Math.max(chosen.mode, LOCKOUT_FLOOR) + cast
          : Math.max(chosen.mode, LOCKOUT_FLOOR + cast)
        : undefined

      if (!chosen || value === undefined) {
        // Separate from NO DATA: cast, but never twice by one instance and never kicked.
        const casts = sample.timelines.reduce((total, t) => total + t.length, 0)
        const verdict = `NO INTERVAL (${sample.timelines.length} instances, ${casts} events)`
        rows.push(`${abilityId}\t-\t-\t-\t${verdict}\t${label}`)
        continue
      }

      const confident = chosen.samples >= MIN_SAMPLES
      const gap = source === 'post-kick' ? Math.max(chosen.mode, LOCKOUT_FLOOR) : value
      const floored = chosen.mode < gap ? ` floored from ${chosen.mode}s` : ''
      const plusCast = source === 'post-kick' && cast ? ` +${cast}s cast` : ''
      const how = `${source}/${chosen.statistic} ${gap}s${floored}${plusCast}`
      const verdict = confident
        ? `ok (${how})`
        : `LOW CONFIDENCE (${chosen.samples} samples, ${how})`

      rows.push(`${abilityId}\t${value}\t${chosen.samples}\t${source}\t${verdict}\t${label}`)

      // A spell id can be shared by several mobs (ToS Lightning Bolt), and the data is keyed by
      // spell, so keep the better-sampled estimate rather than whichever mob came last.
      if (confident && chosen.samples > (mined.get(abilityId)?.samples ?? 0)) {
        mined.set(abilityId, { cooldown: value, samples: chosen.samples })
      }

      console.log(`\n${label}`)
      console.log(
        `  ${sample.timelines.length} instances — ` +
          `post-kick ${postKick ? `${postKick.mode}s (n=${postKick.samples})` : '-'}, ` +
          `natural recast ${natural ? `${natural.mode}s (n=${natural.samples})` : '-'} ` +
          `→ using ${value}s (${source})`,
      )
      for (const [bin, count] of [...chosen.bins].sort((a, b) => a[0] - b[0])) {
        console.log(`    ${bin.toFixed(1).padStart(6)}s  ${'#'.repeat(count)} ${count}`)
      }
    }
  }

  console.log(`\n--- ${dungeonKey} coverage ---`)
  console.log('spellId\tinterval\tn\tsource\tverdict\tmob — spell')
  for (const row of rows.sort()) {
    console.log(row)
  }
}

/**
 * Rewrites the generated module, preserving entries for dungeons this run didn't touch. Processed
 * dungeons are pruned first so stale spells don't linger.
 */
async function writeMined(processed: DungeonKey[]) {
  const { minedCooldowns } = await import('../src/data/spells/spellCooldownsMined.ts')

  const merged = new Map<number, number>(
    Object.entries(minedCooldowns).map(([id, cooldown]) => [Number(id), cooldown]),
  )

  for (const dungeonKey of processed) {
    for (const spellIds of interruptibleSpells(dungeonKey).values()) {
      for (const spellId of spellIds) {
        merged.delete(spellId)
      }
    }
  }

  for (const [spellId, { cooldown }] of mined) {
    merged.set(spellId, cooldown)
  }

  // Labels for every dungeon, so carried-over entries stay annotated. A spell id can belong to
  // several mobs, so name them all rather than just whichever was visited last.
  const labelMobs = new Map<number, { dungeonKey: DungeonKey; mobs: Set<string> }>()
  for (const dungeonKey of dungeonKeys) {
    const mobNames = new Map(mdtDungeons[dungeonKey].enemies.map((e) => [e.id, e.name]))
    for (const [gameId, spellIds] of interruptibleSpells(dungeonKey)) {
      for (const spellId of spellIds) {
        const entry = labelMobs.get(spellId) ?? { dungeonKey, mobs: new Set<string>() }
        entry.mobs.add(String(mobNames.get(gameId) ?? gameId))
        labelMobs.set(spellId, entry)
      }
    }
  }

  const labels = new Map(
    [...labelMobs].map(([spellId, { dungeonKey, mobs }]) => [
      spellId,
      `${dungeonKey} ${[...mobs].join(' / ')} — ${spellName(spellId)}`,
    ]),
  )

  const entries = [...merged].sort((a, b) =>
    (labels.get(a[0]) ?? '').localeCompare(labels.get(b[0]) ?? ''),
  )

  const body = entries
    // No sample count: only this run's dungeon has one, which would imply the carried-over entries
    // were less well evidenced. Provenance lives in the coverage table.
    .map(([spellId, interval]) => {
      const cast = castTime(spellId)
      const split = cast ? ` = ${roundTo(interval - cast, 3)}s + ${cast}s cast` : ''
      return `  ${spellId}: ${interval}, // ${labels.get(spellId) ?? 'unknown'}${split}`
    })
    .join('\n')

  const file = `${HEADER}\nexport const minedCooldowns: Record<number, number> = {\n${body}\n}\n`
  await writeFile(MINED_PATH, file, 'utf-8')

  console.log(`\nWrote ${entries.length} cooldowns to ${MINED_PATH}`)
  console.log('Correct or exclude anything questionable in src/data/spells/spellCooldowns.ts.')
}

const processed: DungeonKey[] = []
for (const dungeonKey of dungeonKeys) {
  if (!filterDungeonKey || dungeonKey === filterDungeonKey) {
    await guessDungeonCooldowns(dungeonKey)
    processed.push(dungeonKey)
  }
}

await writeMined(processed)
